[32mINFO    [0m root:test_add.py:45 å¼€å§‹è°ƒç”¨å‡½æ•°('æ–‡', 9.3, 'TypeError')